---
title: Living Water Cottage
short_title: Living Water Cottage
description: Living Water Cottage, Franklin, TN
baseurl: 
permalink: "/:path/"
incremental: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:path/"
jekyll-archives:
  enabled: all
  layout: archive
plugins:
- jekyll-menus
- jekyll-feed
- jekyll-archives
